"""
video_generator.py — Explainer Video Generation
================================================
Slide duration and total video length are derived from the actual
content — longer text = more slides = longer video.

Reading speed assumption: ~150 words per minute (comfortable narration pace).
Each slide's duration = time needed to read its body text aloud + 2s padding.
Minimum slide duration: 5s. Maximum: 20s.

Course: Advanced Topics in Machine Learning (HTML)
"""

import logging
import textwrap
from pathlib import Path

import nltk

log = logging.getLogger(__name__)

VIDEO_W, VIDEO_H   = 640, 360
FPS                = 10
WORDS_PER_MINUTE   = 150          # narration reading speed
MIN_SLIDE_DURATION = 4            # seconds
MAX_SLIDE_DURATION = 10           # seconds
PADDING_SECONDS    = 1            # extra buffer per slide

FONT_SIZE_TITLE = 22
FONT_SIZE_BODY  = 16

BG_COLOR     = (11, 17, 32)
ACCENT_COLOR = (245, 158, 11)
BODY_COLOR   = (176, 190, 197)
TITLE_COLOR  = (240, 244, 248)


# ─── DURATION HELPER ────────────────────────────────────────────

def _slide_duration(body_text: str) -> float:
    """
    Calculate how long a slide should display based on word count.
    duration = (words / 150wpm * 60) + 2s padding, clamped to [5, 20].
    """
    words = len(body_text.split())
    reading_time = (words / WORDS_PER_MINUTE) * 60
    return max(MIN_SLIDE_DURATION, min(MAX_SLIDE_DURATION, reading_time + PADDING_SECONDS))


# ─── PIL SLIDE RENDERING ────────────────────────────────────────

def _get_font(size: int, bold: bool = False):
    from PIL import ImageFont
    candidates = [
        "C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold
        else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
    ]
    for path in candidates:
        if Path(path).exists():
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                pass
    return ImageFont.load_default()


def render_slide(title: str, body: str, slide_num: int, total: int):
    from PIL import Image, ImageDraw

    img  = Image.new("RGB", (VIDEO_W, VIDEO_H), BG_COLOR)
    draw = ImageDraw.Draw(img)

    # Grid background
    grid_color = (17, 24, 39)
    for x in range(0, VIDEO_W, 48):
        draw.line([(x, 0), (x, VIDEO_H)], fill=grid_color, width=1)
    for y in range(0, VIDEO_H, 48):
        draw.line([(0, y), (VIDEO_W, y)], fill=grid_color, width=1)

    draw.rectangle([48, 80, 54, VIDEO_H - 80], fill=ACCENT_COLOR)

    counter_font = _get_font(16)
    draw.text((VIDEO_W - 80, 30), f"{slide_num} / {total}",
              font=counter_font, fill=(75, 85, 99))

    title_font = _get_font(FONT_SIZE_TITLE, bold=True)
    title_y    = 100
    draw.text((80, title_y), title, font=title_font, fill=TITLE_COLOR)

    title_bbox = draw.textbbox((80, title_y), title, font=title_font)
    draw.line([(80, title_bbox[3] + 8), (title_bbox[2], title_bbox[3] + 8)],
              fill=ACCENT_COLOR, width=2)

    body_font = _get_font(FONT_SIZE_BODY)
    wrapped   = textwrap.fill(body, width=65)
    draw.multiline_text((80, title_bbox[3] + 32), wrapped,
                        font=body_font, fill=BODY_COLOR, spacing=10)

    brand_font = _get_font(18)
    draw.text((80, VIDEO_H - 40), "ScholarAI · Advanced Topics in ML",
              font=brand_font, fill=(55, 65, 81))

    return img


# ─── SLIDE SEGMENTATION ─────────────────────────────────────────

def _segment_summary(summary: str, sentences_per_slide: int = 3) -> list[tuple[str, str]]:
    """
    Split summary into slides. More content → more slides → longer video.
    sentences_per_slide controls granularity (3 = ~60-90 words per slide).
    """
    try:
        sentences = nltk.sent_tokenize(summary)
    except Exception:
        sentences = summary.split(". ")

    slides = [("Document Summary", "Generated by ScholarAI ML Pipeline")]
    chunks = [sentences[i:i + sentences_per_slide]
              for i in range(0, len(sentences), sentences_per_slide)]

    for i, chunk in enumerate(chunks):
        slides.append((f"Key Point {i + 1}", " ".join(chunk)))

    slides.append(("End of Summary",
                   "Generated by ScholarAI · Powered by BART + Sentence-BERT"))
    return slides


# ─── VIDEO ASSEMBLY ─────────────────────────────────────────────

def generate_video(summary: str, output_path: str) -> tuple[str, dict]:
    """
    Generate video with metadata about the generation process.
    
    Returns:
        tuple: (output_path, metadata_dict)
        metadata_dict contains:
            - status: "video_ok" | "slides_only" | "placeholder"
            - message: Human-readable description
            - slides_url: Path to slides ZIP if available
    """
    metadata = {"status": "placeholder", "message": "", "slides_url": None}
    try:
        # Point moviepy at the imageio-ffmpeg bundled binary so ffmpeg
        # doesn't need to be installed system-wide / in PATH.
        try:
            import imageio_ffmpeg
            import moviepy.config as mpy_conf
            mpy_conf.change_settings({"FFMPEG_BINARY": imageio_ffmpeg.get_ffmpeg_exe()})
        except Exception as _fe:
            log.warning(f"Could not set bundled ffmpeg path: {_fe}")

        import numpy as np
        from moviepy.editor import AudioFileClip, ImageClip, concatenate_videoclips

        segments = _segment_summary(summary, sentences_per_slide=3)
        log.info(f"Rendering {len(segments)} slides…")

        clips = []
        for i, (title, body) in enumerate(segments):
            duration  = _slide_duration(body)
            pil_img   = render_slide(title, body, i + 1, len(segments))
            img_array = np.array(pil_img)
            clip = (ImageClip(img_array)
                    .set_duration(duration)
                    .set_fps(FPS)
                    .fadein(0.4)
                    .fadeout(0.4))
            clips.append(clip)
            log.info(f"  Slide {i+1}: '{title}' — {len(body.split())} words → {duration:.1f}s")

        final = concatenate_videoclips(clips, method="compose")
        total_duration = sum(c.duration for c in clips)
        log.info(f"Total video duration: {total_duration:.1f}s ({len(segments)} slides)")

        # ── TTS narration ──────────────────────────────────────
        audio_path = output_path.replace(".mp4", "_narration.mp3")
        audio_clip = None
        try:
            from .tts_generator import generate_audio
            success = generate_audio(summary, audio_path)

            wav_alt = audio_path.replace(".mp3", ".wav")
            actual_audio = audio_path if Path(audio_path).exists() else wav_alt

            if success and Path(actual_audio).exists() and Path(actual_audio).stat().st_size > 500:
                audio_clip = AudioFileClip(actual_audio)
                audio_dur  = audio_clip.duration
                video_dur  = final.duration

                if audio_dur < video_dur:
                    try:
                        from moviepy.audio.fx.all import audio_loop
                        audio_clip = audio_loop(audio_clip, duration=video_dur)
                    except Exception:
                        # Fallback: just let the audio end early
                        pass
                else:
                    audio_clip = audio_clip.subclip(0, video_dur)

                final = final.set_audio(audio_clip)
                log.info(f"Audio added: {audio_dur:.1f}s audio over {video_dur:.1f}s video")

        except Exception as e:
            log.warning(f"Could not add audio to video: {type(e).__name__}: {e}")

        # ── Export ─────────────────────────────────────────────
        final.write_videofile(
            output_path,
            fps=FPS,
            codec="libx264",
            audio_codec="aac" if audio_clip is not None else None,
            temp_audiofile=output_path + ".temp.m4a" if audio_clip is not None else None,
            remove_temp=True,
            logger=None,
            verbose=False,
            ffmpeg_params=["-crf", "35", "-preset", "ultrafast"]
        )

        if audio_clip is not None:
            try: audio_clip.close()
            except Exception: pass

        # Cleanup narration temp file
        for p in [audio_path, audio_path.replace(".mp3", ".wav")]:
            try:
                if Path(p).exists(): Path(p).unlink()
            except Exception: pass

        log.info(f"Video saved → {output_path}")
        metadata["status"] = "video_ok"
        metadata["message"] = "Video generated successfully"
        return output_path, metadata

    except ImportError as e:
        log.warning(f"MoviePy/PIL not available: {e}. Writing slideshow fallback.")
        zip_path = _write_slideshow_fallback(summary, output_path)
        metadata["status"] = "slides_only"
        metadata["message"] = "MoviePy/PIL not available. Slides exported as ZIP."
        metadata["slides_url"] = zip_path.replace(".mp4", "_slides.zip")
        return output_path, metadata
    except Exception as e:
        log.error(f"Video generation failed: {e}", exc_info=True)
        zip_path = _write_slideshow_fallback(summary, output_path)
        metadata["status"] = "slides_only"
        metadata["message"] = f"Video generation failed: {e}. Slides exported as ZIP."
        metadata["slides_url"] = zip_path.replace(".mp4", "_slides.zip")
        return output_path, metadata


# ─── FALLBACK: SLIDES ZIP ───────────────────────────────────────

def _write_slideshow_fallback(summary: str, output_path: str) -> str:
    """Returns the zip_path."""
    try:
        import io
        import zipfile

        segments = _segment_summary(summary)
        zip_path = output_path.replace(".mp4", "_slides.zip")

        with zipfile.ZipFile(zip_path, "w") as zf:
            for i, (title, body) in enumerate(segments):
                pil_img = render_slide(title, body, i + 1, len(segments))
                buf = io.BytesIO()
                pil_img.save(buf, format="PNG")
                zf.writestr(f"slide_{i+1:02d}.png", buf.getvalue())

        log.info(f"Slideshow ZIP saved → {zip_path}")
        Path(output_path).write_text(f"[Slides exported as {zip_path}]")
        return zip_path

    except Exception:
        Path(output_path).write_text(
            "[PLACEHOLDER] Install moviepy and pillow to generate video.\n"
            f"Summary:\n{summary[:400]}"
        )
        return output_path
